module.exports = {
    BankWire: 'BANK_WIRE',
    Card: 'CARD',
    DirectDebit: 'DIRECT_DEBIT',
    Preauthorized: 'PREAUTHORIZED',
    PayPal: 'PAYPAL',
    ApplePay: 'APPLEPAY',
    GooglePay: 'GOOGLE_PAY',
    Mbway: 'MBWAY',
    Bancontact: 'BCMC',
    Bizum: 'BIZUM',
    Multibanco: 'MULTIBANCO',
    Satispay: 'SATISPAY',
    Blik: 'BLIK',
    Klarna: 'KLARNA',
    Ideal: 'IDEAL',
    Giropay: 'GIROPAY',
    Swish: 'SWISH',
    Twint: 'TWINT'
};
